### ISSUE TITLE
Releasing final coefficients

### ISSUE THREAD

**Issue by smithara** [IAGA-VMOD/IGRF14eval#44]
I imagine we can start with storing the finalised coefficients here under ` IGRF14eval/data/coefficients`:
```
DGRF_Final.cof
IGRF_Final.cof
SV_Final.cof
```

We then need to create the various formats that are used for dissemination:
1. `igrf14coeffs.txt` (see [igrf13coeffs.txt](https://www.ngdc.noaa.gov/IAGA/vmod/coeffs/igrf13coeffs.txt))
2. `IGRF14coeffs.xls` (see [IGRF13coeffs.xls](https://www.ngdc.noaa.gov/IAGA/vmod/coeffs/IGRF13coeffs.xls)
3. `IGRF14.shc` (see e.g. [IGRF13.shc](https://github.com/klaundal/ppigrf/blob/main/src/ppigrf/IGRF13.shc))
4. ... ?
5. 
I think these can be bundled together in one Zenodo archive. It will also be good to put some code used to generate these formats in this repository. I expect to archive this repository on Zenodo as well, so that the final publication can reference both this repo as a software artifact and the final coefficients as a "data" artifact.

(I made a start on the "release process" task list at https://github.com/IAGA-VMOD#release-process)

When I started drafting the Zenodo release (for the final coefficients - reserved DOI `10.5281/zenodo.14012303`), I found some things we need to decide:
1. License
  I guess this has just been glossed over before, but I *think* it should be [CC0](https://creativecommons.org/publicdomain/zero/1.0/legalcode) - basically that it's fully public domain and can be used without citation
2. Authorship
  I expect to fill in the list of all the authors here, though I can also add "IAGA V-MOD" itself as an organisation. There is the option to describe different roles both for [creators](https://help.zenodo.org/docs/deposit/describe-records/creators/) and [contributors](https://help.zenodo.org/docs/deposit/describe-records/contributors/)

**Comment by ciaranbe** [comment]
Super. Thanks for starting the process and pages. 
1) I hadn't come across CC0. We might want to check with the IAGA Executive Committee about that. 
2) With regards to authorship, it is a cast of thousands (well dozens) usually so we won't know until the official IGRF-14 paper is released. Can we modify the creator/contributor list at that stage?

**Comment by smithara** [comment]
I suppose [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) is a likely choice for license, as is [used by Kp](https://doi.org/10.5880/Kp.0001) - it just feels a bit funny to me because in practice these things are used as if they are CC0!

**Comment by smithara** [comment]
The IGRF-14 is now released at https://doi.org/10.5281/zenodo.14012302 and https://www.ncei.noaa.gov/products/international-geomagnetic-reference-field (pending updates to the referenced software and calculators)

This repository is also archived at https://doi.org/10.5281/zenodo.14205633 - we can make more updates by making a [release](https://github.com/IAGA-VMOD/IGRF14eval/releases/) on this repo, and that DOI resolves to the latest release

The announcement has gone out to several mailing lists and we'll follow up with updates to various software separately
